name: Build Python package and publish to PyPI if tagged
on: push

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:

        - name: Checkout
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8

        - name: Install pypa/build
          run: |
            python -m pip install --upgrade pip
            python -m pip install build

        - name: Build binary wheel and source tarbal
          run: python -m build --sdist --wheel --outdir dist/ .

        - name: Publish distribution to PyPI
          if: startsWith(github.ref, 'refs/tags')
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            user: __token__
            password: ${{ secrets.PYPI_API_TOKEN }}
